Candy_SUT21/Candy_SUT21/Controllers/CandyController.cs
using Candy_SUT21.Models;
using Candy_SUT21.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Candy_SUT21.Controllers
{
    public class CandyController : Controller 
    {
        private readonly ICandyRepository _candyRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CandyController(ICandyRepository candyRepository , ICategoryRepository categoryRepository)
        {
            _candyRepository = candyRepository;
            _categoryRepository = categoryRepository;
        }

       //public IActionResult List() 
       // {
       //     //ViewBag.CurrnetCategory = "BestSellers";


       //     var candyListViewModel = new CandyListViewModel();
       //     candyListViewModel.Candies = _candyRepository.GetAllCandy;
       //     candyListViewModel.CurrentCategory = "BestSeller";
       //     return View(candyListViewModel);
       //}

        public ViewResult List(string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetAllCategory.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var candy = _candyRepository.GetCandyById(id);
            if (candy == null)
            {
                return NotFound();
            }

            return View(candy);
        }
    }
}

Candy_SUT21/Candy_SUT21/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Candy_SUT21.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Candy_SUT21/Candy_SUT21/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Candy_SUT21/Candy_SUT21/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    </head>
    <body>
       <div class="container">
           <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
               <div class="container">
                   <div class="navbar-header">
                       <button type="button" class="navbar-toggle" data-toggle="collapse">
                           <span class="sr-only">Toggle navigation</span>
                           <span class="icon-bar"></span>
                           <span class="icon-bar"></span>
                           <span class="icon-bar"></span>
                       </button>
                   </div>
                   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
                       <ul class="nav navbar-nav">
                           <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                           @await Component.InvokeAsync("CategoryMenu");
                           <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                           @await Component.InvokeAsync("ShoppingCartSummary")
                           <partial name="_LoginPartial"/>
                       </ul>

                   

                   </div>

               </div>
           </nav>
       </div>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src=~/Images/candyshoplogo.png />
                </p>
            </div>

            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>

        @*<div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>*@

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - Candy_SUT21 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>

Candy_SUT21/Candy_SUT21/Views/Shared/_candycard.cshtml
@model Candy


<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="Image for Candy" />

        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Candy" asp-action="Details" asp-route-id="@Model.CandyId">@Model.Name</a></h3>
            <p>@Model.Description</p>
        </div>

        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                asp-controller="ShoppingCart"
                asp-action="AddToShoppingCart"
                asp-route-candyId=@Model.CandyId
                >Add to cart</a>
            </p>
        </div>
    </div>
</div>